name: quran_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: ^0.13.5
  lottie: 2.2.0
  shared_preferences: 2.0.17
  just_audio: 0.9.31
  sqflite: 2.2.5
  path_provider: 2.0.13
  scroll_to_index: 3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/image/
  uses-material-design: true

